In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import keras 
from keras.models import * 
from keras.layers import * 
from keras.preprocessing import image
import PIL
from keras.callbacks import EarlyStopping

In [4]:
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale=1./255,)
test_datagen = ImageDataGenerator(rescale=1./255)

In [7]:
!wget http://cb.lk/covid_19
!unzip covid_19

--2022-09-15 11:24:23--  http://cb.lk/covid_19
Resolving cb.lk (cb.lk)... 172.67.187.81, 104.21.72.203, 2606:4700:3032::ac43:bb51, ...
Connecting to cb.lk (cb.lk)|172.67.187.81|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://cb.lk/covid_19 [following]
--2022-09-15 11:24:23--  https://cb.lk/covid_19
Connecting to cb.lk (cb.lk)|172.67.187.81|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.dropbox.com/s/7rjw6oet4za01op/CovidDataset-20200427T133042Z-001.zip?dl=0 [following]
--2022-09-15 11:24:24--  https://www.dropbox.com/s/7rjw6oet4za01op/CovidDataset-20200427T133042Z-001.zip?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.6.18, 2620:100:6019:18::a27d:412
Connecting to www.dropbox.com (www.dropbox.com)|162.125.6.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/7rjw6oet4za01op/CovidDataset-20200427T133042Z-001.zip [following]
--2022-09-15 11:24:24

In [8]:
train_set = train_datagen.flow_from_directory('/content/CovidDataset/Train/',
      target_size=(224, 224), batch_size=32, class_mode='categorical', shuffle=False)

Found 224 images belonging to 2 classes.


In [10]:
test_set = test_datagen.flow_from_directory('/content/CovidDataset/Val/',
     target_size=(224, 224), batch_size=32,class_mode='categorical', shuffle=False)

Found 60 images belonging to 2 classes.


In [11]:
 model=keras.Sequential()
 model.add(Conv2D(input_shape=(224,224,3),filters=64,kernel_size=(3,3),padding="same", activation="relu"))
 model.add(Conv2D(filters=64,kernel_size=(3,3),padding="same", activation="relu"))
 model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
 model.add(Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"))
 model.add(Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"))
 model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
 model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
 model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
 model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
 model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
 model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
 model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
 model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
 model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
 model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
 model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
 model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
 model.add(MaxPool2D(pool_size=(2,2),strides=(2,2),name='vgg16'))
 model.add(Flatten(name='flatten'))
 model.add(Dense(4096, activation='relu', name='fc1'))
 model.add(Dense(4096, activation='relu', name='fc2'))
 model.add(Dense(2, activation='softmax', name='output'))

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 224, 224, 64)      1792      
                                                                 
 conv2d_1 (Conv2D)           (None, 224, 224, 64)      36928     
                                                                 
 max_pooling2d (MaxPooling2D  (None, 112, 112, 64)     0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 112, 112, 128)     73856     
                                                                 
 conv2d_3 (Conv2D)           (None, 112, 112, 128)     147584    
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 56, 56, 128)      0         
 2D)                                                    

In [ ]:
model.compile(loss=keras.losses.categorical_crossentropy, optimizer="sgd", metrics=['accuracy'])

results=model.fit( 
    train_set,  
    epochs=10,
    validation_data=test_set,steps_per_epoch=len(train_set),validation_steps=len(test_set),
    callbacks=keras.callbacks.EarlyStopping(patience=3,restore_best_weights=True)      
  )


Epoch 1/10
7/7 [==============================] - 24s 2s/step - loss: 0.6988 - accuracy: 0.3571 - val_loss: 0.6925 - val_accuracy: 0.5000
Epoch 2/10
7/7 [==============================] - 9s 1s/step - loss: 0.6973 - accuracy: 0.2188 - val_loss: 0.6921 - val_accuracy: 0.7167
Epoch 3/10
7/7 [==============================] - 9s 1s/step - loss: 0.6969 - accuracy: 0.5045 - val_loss: 0.6917 - val_accuracy: 0.9500
Epoch 4/10
7/7 [==============================] - 9s 1s/step - loss: 0.6966 - accuracy: 0.5536 - val_loss: 0.6915 - val_accuracy: 0.9500
Epoch 5/10
7/7 [==============================] - 9s 1s/step - loss: 0.6962 - accuracy: 0.5580 - val_loss: 0.6912 - val_accuracy: 0.9333
Epoch 6/10
7/7 [==============================] - 8s 1s/step - loss: 0.6951 - accuracy: 0.5000 - val_loss: 0.6913 - val_accuracy: 0.5000
Epoch 7/10
7/7 [==============================] - 9s 1s/step - loss: 0.6962 - accuracy: 0.3661 - val_loss: 0.6908 - val_accuracy: 0.5833
Epoch 8/10
7/7 [========================

In [ ]:
model.evaluate(test_set)

2/2 [==============================] - 2s 560ms/step - loss: 0.6897 - accuracy: 0.9667


[0.689737856388092, 0.9666666388511658]

In [ ]:
model.save('/content/drive/MyDrive/SavedModels/vgg16_Covid19.h5')

In [ ]:
y_pred= model.predict(test_set)
y_pred

array([[0.5018649 , 0.4981351 ],
       [0.5025482 , 0.4974518 ],
       [0.50184053, 0.4981595 ],
       [0.50298166, 0.49701834],
       [0.5023587 , 0.4976413 ],
       [0.5025305 , 0.49746948],
       [0.5031993 , 0.49680066],
       [0.50189805, 0.49810192],
       [0.5040472 , 0.4959528 ],
       [0.5028866 , 0.4971134 ],
       [0.5012515 , 0.49874848],
       [0.503201  , 0.496799  ],
       [0.5020464 , 0.49795356],
       [0.501856  , 0.49814397],
       [0.5027052 , 0.49729478],
       [0.50018287, 0.4998171 ],
       [0.5031624 , 0.4968376 ],
       [0.5022691 , 0.4977309 ],
       [0.50270444, 0.49729556],
       [0.50301707, 0.496983  ],
       [0.50259876, 0.49740124],
       [0.5019709 , 0.49802908],
       [0.50263864, 0.49736133],
       [0.5022632 , 0.49773684],
       [0.5030731 , 0.49692687],
       [0.5025641 , 0.49743593],
       [0.502178  , 0.49782193],
       [0.50218564, 0.4978144 ],
       [0.5029852 , 0.49701485],
       [0.50072193, 0.49927807],
       [0.

In [ ]:
import numpy as np
y_pred1=np.argmax(y_pred,axis=1)
y_pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [ ]:
from sklearn.metrics import accuracy_score,  confusion_matrix
print(confusion_matrix(test_set.labels,y_pred1))

accuracy_score(test_set.labels,y_pred1)*100

[[30  0]
 [ 2 28]]


96.66666666666667