In [2]:
from tensorflow import keras
from keras.layers import Input, Dense, Dropout,Conv2D, MaxPooling2D, Flatten
from tensorflow.keras import  datasets
from matplotlib import pyplot as plt

In [3]:
(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

170508288/170498071 [==============================] - 4s 0us/step


In [4]:
x_train.shape

(50000, 32, 32, 3)

In [5]:
x_test.shape

(10000, 32, 32, 3)

In [6]:
#Normalize image pixel values.
x_train = x_train/255
x_test = x_test/255

In [19]:
model=keras.Sequential() #Create a network sequence.

model.add(Input(shape=(32,32,3)))
model.add(Conv2D(64, (3, 3), padding='same',activation='relu'))
#model.add(Conv2D(32, (3, 3), padding='same', activation='relu', input_shape=(32,32,3)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(Dropout(0.25))
model.add(Conv2D(32, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(96, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(32, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(16, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(8, (3, 3), padding='same', activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Conv2D(96, (3, 3), activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2)))


model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(400, activation='relu'))
model.add(Dense(120, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(10, activation='softmax'))
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_71 (Conv2D)          (None, 32, 32, 64)        1792      
                                                                 
 conv2d_72 (Conv2D)          (None, 30, 30, 32)        18464     
                                                                 
 dropout_36 (Dropout)        (None, 30, 30, 32)        0         
                                                                 
 conv2d_73 (Conv2D)          (None, 30, 30, 32)        9248      
                                                                 
 conv2d_74 (Conv2D)          (None, 28, 28, 96)        27744     
                                                                 
 max_pooling2d_27 (MaxPoolin  (None, 14, 14, 96)       0         
 g2D)                                                            
                                                     

In [21]:
model.compile(optimizer='Adam',loss="sparse_categorical_crossentropy",metrics=['accuracy']) 
results= model.fit(x_train,y_train,epochs=30,batch_size=100,validation_data=(x_test, y_test))



Epoch 1/30
500/500 [==============================] - 10s 18ms/step - loss: 1.6040 - accuracy: 0.4145 - val_loss: 1.4451 - val_accuracy: 0.4695
Epoch 2/30
500/500 [==============================] - 9s 18ms/step - loss: 1.4509 - accuracy: 0.4769 - val_loss: 1.2952 - val_accuracy: 0.5242
Epoch 3/30
500/500 [==============================] - 9s 18ms/step - loss: 1.3304 - accuracy: 0.5272 - val_loss: 1.1876 - val_accuracy: 0.5746
Epoch 4/30
500/500 [==============================] - 9s 18ms/step - loss: 1.2357 - accuracy: 0.5644 - val_loss: 1.1397 - val_accuracy: 0.5947
Epoch 5/30
500/500 [==============================] - 9s 18ms/step - loss: 1.1561 - accuracy: 0.5948 - val_loss: 1.0605 - val_accuracy: 0.6281
Epoch 6/30
500/500 [==============================] - 9s 18ms/step - loss: 1.0889 - accuracy: 0.6226 - val_loss: 1.0706 - val_accuracy: 0.6300
Epoch 7/30
500/500 [==============================] - 9s 18ms/step - loss: 1.0276 - accuracy: 0.6423 - val_loss: 1.0151 - val_accuracy: 0.655

In [ ]:
score = model.evaluate(x_test, y_test)


313/313 [==============================] - 8s 26ms/step - loss: 0.5881 - accuracy: 0.8019


In [ ]:
y_pred=model.predict(x_test)
y_pred[0:3]

array([[2.7163900e-04, 3.2132107e-03, 1.4195467e-03, 6.9616461e-01,
        3.4877294e-04, 2.6107654e-01, 3.5315517e-02, 1.1790473e-03,
        6.1826344e-04, 3.9288329e-04],
       [1.0811333e-02, 1.0433994e-01, 4.1965663e-07, 4.4686685e-06,
        1.2815647e-07, 3.1810014e-08, 5.5820863e-08, 2.4172530e-07,
        8.7238210e-01, 1.2461284e-02],
       [1.9053901e-02, 3.0300581e-01, 1.2978271e-04, 1.0896876e-03,
        2.1764536e-05, 5.6710844e-05, 7.3824012e-05, 1.3517588e-04,
        6.2272805e-01, 5.3705323e-02]], dtype=float32)

In [ ]:
import numpy as np
from numpy import argmax
y_pred1=argmax(y_pred,axis=1)
y_pred1[0:3]

array([3, 8, 8])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_pred1,y_test))
print(accuracy_score(y_pred1,y_test))

[[859   6  76  25  10  16   9  16  67  22]
 [ 12 938   2   8   4   2   3   0  40  60]
 [ 19   1 641  40  39  23  31   7   8   4]
 [  8   3  38 596  44  95  43  20   9  10]
 [ 14   0  78  49 769  36  18  35   3   4]
 [  3   3  70 168  35 754  19  35   2   1]
 [  4   8  52  59  37  18 864   7   4   4]
 [ 16   2  30  33  56  47   7 876   2   4]
 [ 38   5   4  13   4   5   3   1 843  12]
 [ 27  34   9   9   2   4   3   3  22 879]]
0.8019
