In [1]:
from tensorflow import keras
from keras.layers import Input, Dense, Dropout,Conv2D, MaxPool2D, Flatten
from tensorflow.keras import  datasets
from matplotlib import pyplot as plt

In [2]:
(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

170508288/170498071 [==============================] - 14s 0us/step


In [3]:
x_train.shape

(50000, 32, 32, 3)

In [4]:
x_test.shape

(10000, 32, 32, 3)

In [5]:
#Normalize image pixel values.
x_train = x_train/255
x_test = x_test/255

In [17]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from tensorflow.keras import regularizers, optimizers


model_2 = Sequential()
model_2.add(Conv2D(64,(4,4),input_shape=(32,32,3),activation='relu'))
model_2.add(Conv2D(64,(4,4),input_shape=(32,32,3),activation='relu'))
model_2.add(MaxPooling2D(pool_size=(2,2)))
model_2.add(Dropout(0.4))
model_2.add(Conv2D(128,(4,4),input_shape=(32,32,3),activation='relu'))
model_2.add(Conv2D(128,(4,4),input_shape=(32,32,3),activation='relu'))
model_2.add(MaxPooling2D(pool_size=(2,2)))
model_2.add(Dropout(0.4))
model_2.add(Flatten())
model_2.add(Dense(1024,activation='relu'))
model_2.add(Dense(1024,activation='relu'))
model.add(Dense(10, activation = 'softmax'))
model_2.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 32, 32, 32)        896       
                                                                 
 conv2d_1 (Conv2D)           (None, 32, 32, 32)        9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 16, 16, 32)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 16, 16, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 16, 16, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 8, 8, 64)         0         
 2D)                                                  

In [19]:

results= model.fit(x_train,y_train,epochs=20,batch_size=30,validation_data=(x_test, y_test))



Epoch 1/20
1667/1667 [==============================] - 10s 6ms/step - loss: 0.9953 - accuracy: 0.5900 - val_loss: 1.1814 - val_accuracy: 0.5603
Epoch 2/20
1667/1667 [==============================] - 9s 6ms/step - loss: 0.8507 - accuracy: 0.6466 - val_loss: 1.1750 - val_accuracy: 0.5917
Epoch 3/20
1667/1667 [==============================] - 9s 6ms/step - loss: 0.8079 - accuracy: 0.6747 - val_loss: 1.1761 - val_accuracy: 0.5847
Epoch 4/20
1667/1667 [==============================] - 9s 6ms/step - loss: 0.7650 - accuracy: 0.6950 - val_loss: 1.1911 - val_accuracy: 0.5958
Epoch 5/20
1667/1667 [==============================] - 9s 6ms/step - loss: 0.7328 - accuracy: 0.7159 - val_loss: 1.1265 - val_accuracy: 0.6142
Epoch 6/20
1667/1667 [==============================] - 9s 6ms/step - loss: 0.7013 - accuracy: 0.7297 - val_loss: 1.0798 - val_accuracy: 0.6429
Epoch 7/20
1667/1667 [==============================] - 9s 6ms/step - loss: 0.6606 - accuracy: 0.7490 - val_loss: 1.1055 - val_accuracy

In [ ]:
score = model.evaluate(x_test, y_test)


313/313 [==============================] - 1s 3ms/step - loss: 1.0933 - accuracy: 0.6346


In [ ]:
y_pred=model.predict(x_test)
y_pred[0:3]

array([[5.0076237e-04, 2.5611328e-02, 7.5104893e-03, 7.4398118e-01,
        5.1915262e-02, 2.1120299e-02, 1.3639909e-01, 1.7395227e-03,
        1.5302604e-03, 9.6918065e-03],
       [7.9586163e-02, 7.2787303e-01, 1.0314399e-05, 1.2678183e-07,
        2.3594070e-07, 6.7275678e-08, 7.5629551e-08, 1.5355005e-07,
        1.3590303e-01, 5.6626856e-02],
       [6.0242355e-01, 2.9507503e-02, 4.2144451e-03, 4.4598349e-04,
        2.4054117e-04, 5.4159405e-04, 1.4288773e-04, 4.9163942e-04,
        3.1862351e-01, 4.3368381e-02]], dtype=float32)

In [ ]:
import numpy as np
from numpy import argmax
y_pred1=argmax(y_pred,axis=1)
y_pred1[0:3]

array([3, 1, 0])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_pred1,y_test))
print(accuracy_score(y_pred1,y_test))

[[675  21  62  26  25   8   6  23  74  34]
 [ 40 804  16  22  13  10  14  11  59 123]
 [ 62   9 552 107 120 102  69  50  17  20]
 [ 14  10  68 400  55 193  54  42  16   9]
 [ 19   8  88  83 552  62  23  72   9  14]
 [  8   4  61 162  39 471  34  78   9  13]
 [ 20  25  72 114  94  67 765  22  14  20]
 [  3   5  32  26  69  57   6 660   2  16]
 [112  25  27  24  20  17  10   3 757  41]
 [ 47  89  22  36  13  13  19  39  43 710]]
0.6346
