In [1]:
from tensorflow import keras
from keras.layers import Input, Dense, Dropout,Conv2D, MaxPooling2D, Flatten
from tensorflow.keras import  datasets
from matplotlib import pyplot as plt

In [2]:
(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

170508288/170498071 [==============================] - 14s 0us/step


In [3]:
x_train.shape

(50000, 32, 32, 3)

In [4]:
x_test.shape

(10000, 32, 32, 3)

In [5]:
#Normalize image pixel values.
x_train = x_train/255
x_test = x_test/255

In [30]:
model=keras.Sequential() #Create a network sequence.

model.add(Input(shape=(32,32,3)))
model.add(Conv2D(50, (3, 3), activation='relu'))
#model.add(Conv2D(32, (3, 3), activation='relu',input_shape = (32,32,3)))
model.add(Conv2D(40, (3, 3), activation='linear', padding = 'same'))
model.add(Conv2D(30, (3, 3), activation='linear', padding = 'valid'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(28, (3, 3), activation='relu',padding = 'valid'))

model.add(Conv2D(43, (3, 3), activation='relu',padding = 'valid'))
model.add(Conv2D(30, (3, 3), activation='linear',padding = 'same'))


model.add(MaxPooling2D((2, 2)))

model.add(Flatten())
model.add(Dense(60,activation = 'relu'))
model.add(Dense(40,activation = 'relu'))
model.add(Dense(30,activation = 'relu'))
model.add(Dense(20,activation = 'linear'))
model.add(Dense(10,activation = 'softmax'))

model.summary()

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_90 (Conv2D)          (None, 30, 30, 50)        1400      
                                                                 
 conv2d_91 (Conv2D)          (None, 30, 30, 40)        18040     
                                                                 
 conv2d_92 (Conv2D)          (None, 28, 28, 30)        10830     
                                                                 
 max_pooling2d_41 (MaxPoolin  (None, 14, 14, 30)       0         
 g2D)                                                            
                                                                 
 conv2d_93 (Conv2D)          (None, 12, 12, 28)        7588      
                                                                 
 conv2d_94 (Conv2D)          (None, 10, 10, 43)        10879     
                                                     

In [31]:
model.compile(optimizer='Adam',loss="sparse_categorical_crossentropy",metrics=['accuracy']) 
results= model.fit(x_train,y_train,epochs=30,batch_size=128,validation_data=(x_test, y_test))



Epoch 1/30
391/391 [==============================] - 7s 17ms/step - loss: 1.6642 - accuracy: 0.3874 - val_loss: 1.4357 - val_accuracy: 0.4741
Epoch 2/30
391/391 [==============================] - 6s 15ms/step - loss: 1.2716 - accuracy: 0.5436 - val_loss: 1.1840 - val_accuracy: 0.5757
Epoch 3/30
391/391 [==============================] - 6s 14ms/step - loss: 1.0931 - accuracy: 0.6082 - val_loss: 1.0986 - val_accuracy: 0.6083
Epoch 4/30
391/391 [==============================] - 6s 14ms/step - loss: 0.9645 - accuracy: 0.6574 - val_loss: 0.9765 - val_accuracy: 0.6542
Epoch 5/30
391/391 [==============================] - 6s 14ms/step - loss: 0.8737 - accuracy: 0.6885 - val_loss: 0.9178 - val_accuracy: 0.6788
Epoch 6/30
391/391 [==============================] - 6s 14ms/step - loss: 0.8019 - accuracy: 0.7144 - val_loss: 0.9051 - val_accuracy: 0.6843
Epoch 7/30
391/391 [==============================] - 6s 14ms/step - loss: 0.7494 - accuracy: 0.7355 - val_loss: 0.8575 - val_accuracy: 0.6998

In [32]:
score = model.evaluate(x_test, y_test)


313/313 [==============================] - 1s 4ms/step - loss: 1.3483 - accuracy: 0.6900


In [33]:
y_pred=model.predict(x_test)
y_pred[0:3]

array([[4.17726760e-08, 2.69621575e-10, 6.71048383e-07, 9.93892908e-01,
        2.34621425e-07, 5.94425295e-03, 1.24086815e-04, 5.41153213e-06,
        3.25073015e-05, 1.54521924e-08],
       [3.93640009e-09, 6.00065414e-06, 5.04173266e-11, 2.57181666e-14,
        1.13583525e-08, 4.47412365e-17, 6.82235166e-14, 1.73658245e-12,
        9.99993801e-01, 2.08577333e-07],
       [1.45192206e-01, 2.16349345e-05, 1.71154839e-04, 1.13496717e-05,
        4.54076246e-04, 7.36650492e-08, 1.98302352e-08, 2.34744334e-06,
        8.52800131e-01, 1.34689582e-03]], dtype=float32)

In [14]:
import numpy as np
from numpy import argmax
y_pred1=argmax(y_pred,axis=1)
y_pred1[0:3]

array([3, 8, 8])

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_pred1,y_test))
print(accuracy_score(y_pred1,y_test))

[[700  17  69  20  26   6   8  17  51  21]
 [ 25 878  11   9   4   3   4   6  26 104]
 [ 74   2 567  57  79  43  25  39  13   9]
 [ 22  12  85 555  74 155  64  45  15  15]
 [  9   1  51  37 624  27  22  54   2   1]
 [  5   5  89 219  59 695  25 100   3   9]
 [ 12   6  76  56  60  20 837   8   5  11]
 [  7   0  26  19  54  37   5 704   3   4]
 [105  25  18  15  18   8   5   2 863  37]
 [ 41  54   8  13   2   6   5  25  19 789]]
0.7212
