In [1]:
from tensorflow import keras
from keras.layers import Input, Dense, Dropout,Conv2D, MaxPooling2D, Flatten
from tensorflow.keras import  datasets
from matplotlib import pyplot as plt

In [2]:
(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

170508288/170498071 [==============================] - 14s 0us/step


In [3]:
x_train.shape

(50000, 32, 32, 3)

In [4]:
x_test.shape

(10000, 32, 32, 3)

In [5]:
#Normalize image pixel values.
x_train = x_train/255
x_test = x_test/255

In [ ]:
model=keras.Sequential() #Create a network sequence.

model.add(Input(shape=(32,32,3)))
model.add(Conv2D(32, (3, 3), padding='same',activation='relu'))
#model.add(Conv2D(32, (3, 3), padding='same', activation='relu', input_shape=(32,32,3)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(10, activation='softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 32, 32, 32)        896       
                                                                 
 conv2d_1 (Conv2D)           (None, 30, 30, 32)        9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 15, 15, 32)       0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 15, 15, 32)        0         
                                                                 
 conv2d_2 (Conv2D)           (None, 15, 15, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 13, 13, 64)        36928     
                                                        

In [ ]:
model.compile(optimizer='Adam',loss="sparse_categorical_crossentropy",metrics=['accuracy']) 
results= model.fit(x_train,y_train,epochs=100,batch_size=128,validation_data=(x_test, y_test))



Epoch 1/100
391/391 [==============================] - 6s 13ms/step - loss: 0.5271 - accuracy: 0.8138 - val_loss: 0.5900 - val_accuracy: 0.8000
Epoch 2/100
391/391 [==============================] - 5s 13ms/step - loss: 0.5223 - accuracy: 0.8171 - val_loss: 0.5922 - val_accuracy: 0.7961
Epoch 3/100
391/391 [==============================] - 5s 12ms/step - loss: 0.5106 - accuracy: 0.8191 - val_loss: 0.6235 - val_accuracy: 0.7916
Epoch 4/100
391/391 [==============================] - 5s 13ms/step - loss: 0.5078 - accuracy: 0.8205 - val_loss: 0.5715 - val_accuracy: 0.8066
Epoch 5/100
391/391 [==============================] - 5s 12ms/step - loss: 0.5022 - accuracy: 0.8243 - val_loss: 0.5829 - val_accuracy: 0.8013
Epoch 6/100
391/391 [==============================] - 5s 12ms/step - loss: 0.4970 - accuracy: 0.8228 - val_loss: 0.5860 - val_accuracy: 0.8029
Epoch 7/100
391/391 [==============================] - 5s 12ms/step - loss: 0.4845 - accuracy: 0.8291 - val_loss: 0.5848 - val_accuracy:

In [ ]:
score = model.evaluate(x_test, y_test)


313/313 [==============================] - 1s 3ms/step - loss: 0.6000 - accuracy: 0.7920


In [ ]:
y_pred=model.predict(x_test)
y_pred[0:3]

array([[1.6716817e-04, 3.5730612e-03, 3.9816550e-03, 5.6175917e-01,
        3.7701757e-04, 3.3387491e-01, 9.2604801e-02, 1.5343842e-03,
        1.5635189e-03, 5.6426850e-04],
       [1.3049954e-04, 2.2841530e-05, 7.0941206e-07, 2.5014290e-07,
        8.8193932e-09, 2.3771551e-09, 1.5112181e-07, 8.2418508e-09,
        9.9984312e-01, 2.3835310e-06],
       [1.5631586e-02, 1.8535594e-02, 1.3223164e-03, 2.5967103e-03,
        2.2529456e-04, 4.4453828e-04, 4.1007792e-04, 2.3060340e-04,
        9.5154226e-01, 9.0610255e-03]], dtype=float32)

In [ ]:
import numpy as np
from numpy import argmax
y_pred1=argmax(y_pred,axis=1)
y_pred1[0:3]

array([3, 8, 8])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_pred1,y_test))
print(accuracy_score(y_pred1,y_test))

[[789   6  42   7   9   2   7   8  33  10]
 [ 13 880   2   2   1   0   1   1  24  40]
 [ 36   2 668  52  44  23  35  12  12   4]
 [ 34   4  61 630  76 116  43  45  23  22]
 [ 20   3  58  27 712  21   7  26   5   0]
 [  8   6  74 204  49 792  25  71   6   6]
 [ 10  11  63  49  50  11 872   6   5  11]
 [ 15   1  20  20  54  33   7 828   4   8]
 [ 42  12   7   3   5   1   3   1 862  12]
 [ 33  75   5   6   0   1   0   2  26 887]]
0.792
